import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import UserContext from "@/Context/UserContext";
import { GoogleOAuthProvider } from '@react-oauth/google';

const poppins = Poppins({ subsets: ["latin"], weight: ["300", "400", "500", "600", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GoogleOAuthProvider clientId="656883021391-mkggkpm2bdtog1vt1udld5tssn2buak5.apps.googleusercontent.com">
      <UserContext>
        <html lang="en">
          <body className={poppins.className}>{children}</body>
        </html>
      </UserContext>
    </GoogleOAuthProvider>
  );
}
